
language: cpp
compiler:
    - gcc

before_install:
    #Update GCC please...
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    - sudo apt-get update -qq
    
    #Use recursive cloning, bandit has some submodules (Why its not the default option Travis???)
    - git submodule update --init --recursive

install:
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
    
    - g++ --version
    - g++ -std=c++11 test/test.cpp -o test/test -Wall -pedantic -Isrc -Ibandit
script:
    - cd build
    - ./test --reporter=spec
