language: cpp
compiler:
- gcc
- clang
env:
  global:
  - GCC_VERSION="4.9"
matrix:
- BUILD_TYPE=Debug
- BUILD_TYPE=Release
before_install:
- if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  fi
- if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm;
  fi
- sudo apt-get update -qq
- git submodule update --init --recursive
install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}";
  fi
- if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi
- if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
- if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk
  libcxx; fi
- if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
- if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
- if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
- if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/;
  fi
- if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so;
  fi
- if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd;
  fi
- wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
- bii setup:cpp
- bii --version
script:
- bii open manu343726/edalib-tests
- bii find
- bii cpp:configure -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $CXX)
- bii cpp:build
- "./bin/manu343726_edalib-tests_test --reporter=info"
after_success:
- bii close manu343726/edalib-tests --force
- bii clean
deploy:
  provider: biicode
  user: Manu343726
  password:
    secure: O24y9+IMK6Ip8Zsh4hHdcMSe7nMgZGLHZ3Vjvm7DQqWd5WCrfJIljCytGwfKaYpMbeUytfLqLrPinxaXJjxFzXIwy0XOoOqnsK2r+uRpWyQT/YB2Ubayi3+HKNG0pKC3v02O0nLQcZREC2EJyXISZ9MEAhoPbrFuRmrYfJ7df4g=
